version: '3.7'

services:
  frontend:
    image: dice-web-app/frontend:latest
    build:  
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: dice-web-frontend
    networks:
      - frontend
    ports:
      - "3000:3000"
    #environment:
      #OTEL_SERVICE_NAME: backend-otel
      #OTEL_EXPORTER_OTLP_ENDPOINT:http://collector:4318
      #OTEL_TRACES_EXPORTER: jaeger
      #OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger-service:14250
    depends_on:
      - backend

  backend:
    image: dice-web-app/backend:latest
    build:  
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: dice-web-backend
    networks:
      - backend
      - frontend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongo:27017/
      SPRING_DATA_MONGODB_DATABASE: dicedb
      OTEL_SERVICE_NAME: backend-otel
      # OTEL_EXPORTER_OTLP_ENDPOINT:http://collector:4318
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger-service:14250
    depends_on:
      - mongo

  mongo:
    image: mongo:jammy
    container_name: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - backend
    ports:
      - "4317:4317"
    depends_on:
      - jaeger-service

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    networks:
      - backend
    ports:
      - "16686:16686"
      - "14250"

networks:
  frontend:
  backend: